---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://h1dr0x.github.io/h1dr0x.github.io"
title: "Test Blog"
canonifyurls: true
theme: "Lanyon"
...
