---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://h1dr0x.github.io"
title: "Hugo Blog Template for GitHub Pages"
canonifyurls: false
theme: "Lanyon"
...
